name: Testes automatizados

on:
  pull_request:
    branches: main
  push:
    branches: main
    
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 14.x
      
      - name: Instalar dependencias
        run: yarn install
      
      - name: Rodar testes
        run: yarn test
        
        
        
      
