name: Workflow Principal

on: [workflow_dispatch]


jobs:
  listar-arquivos-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: O que tem neste diretorio ?
        run: |
          ls -lrt
          cat README.md
