name: Workflow Principal

on: [workflow_dispatch]


jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: O que tem neste diretorio ?
        run: |
          ls -lrt
          cat README.md
  
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: O que tem neste diretorio ?
        run: |
          dir
          Get-Content README.md

  depends:
    runs-on: ubuntu-latest
    needs: [windows, ubuntu]
    steps:
      - name: Depende de uma condição
        run: echo "Executou depois da finalização dos jobs"
          
          
